config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
root 'welcome#index'

get 'search' => 'welcome#search'

get 'random' => 'welcome#random'

post 'results' => 'welcome#results'

get 'lexicons' => 'lexicons#index'

get 'lexicons/show' => 'lexicons#show'











end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/lexicon.rb
class Lexicon < ActiveRecord::Base

end

app/models/search.rb
class Search

	def initialize
	end

	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

  def results
		@results = find_results
	end

end

app/controllers/lexicons_controller.rb
class LexiconsController < ApplicationController

	def index
		if params[:category] == nil
      @lexicons = Lexicon.all
    else
      @lexicons = Lexicon.where(category: params[:category])
    end
		@categories = Lexicon.select(:category).distinct
	end

	def show
		@lexicon = Lexicon.where(id: params[:id]).first
	end

	def new
		@lexicon = Lexicon.new
	end

	def edit
		@lexicon = Lexicon.where(id: params[:id])
	end

	def create
		@lexicon = Lexicon.new(lexicon_params)

		respond_to do |format|
			if @lexicon.save
				format.html { redirect_to @lexicon, notice: 'Lexicon was successfully created.'}
				format.json { render :show, status: :created, location: @lexicon }
			else
				format.html { render :new }
				format.json { render json: @lexicon.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@lexicon.destroy
		respond_to do |format|
			format.html { redirect_to lexicons_url, notice: 'lexicon was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		def set_lexicon
			@lexicon = lexicon.find(params[:id])
		end

		def lexicon_params
			params.require(:lexicon).permit(:category, :code, :description, :lexicon_id)
		end
	end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def search
	end

	def random
		@random = Lexicon.find(rand(Lexicon.all.length))
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#individually checks each word entered into the form and returns the entry as a result if >= 70% of the words are included anywhere inside the entry

	def find_results

    ResultsFinder.new(params[:search]).results

		search = params[:search.downcase].split(" ")
		hash = {}
		search.each_with_index do |s, i|
			array = []
			Lexicon.all.each do |entry|
				x = entry.code.to_s.downcase
				y = entry.description.to_s.downcase
				z = x + y
				if z == "" 
					array = array
				elsif z.include?(s)
					array.push(entry)
				end
			hash[i] = array
			end
		end	
		results = []
		total = search.length
		Lexicon.all.each do |entry|
			count = 0
			hash.each do |k, v|
				if v.include?(entry)
					count += 1
				end
			end
			if count/total.to_f >= 0.7
				results.push(entry)
			end
		end
		results
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset=""utf-8"">
  <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"">
  <meta name=""viewport"" content=""width=device-width, initial-scale=1"">
  <title>Code Lexicons</title>
  <link href='https://fonts.googleapis.com/css?family=Codystar|Merriweather:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>"><div class="btn">Home</div></a>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <li class="dropdown">
          <ul class="nav navbar-nav">
            <li><a href="<%= random_path %>"><div class="btn">Random Entry</div></a></li>
            <li><a href="<%= lexicons_path %>"><div class="btn">Choose A Language</div></a></li>
          </ul>
        </li>
        <ul class="nav navbar-nav navbar-right">
          <div class="navbar-form" role="search">
            <%= form_tag(results_path) do %>
              <div class="form-group">
                <%= text_field_tag :search, nil, placeholder: "Search for a Term", class: "form-control" %>
              </div>
              <%= submit_tag "Search", class: "btn btn-primary" %>
            <% end %>
          </div>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  
	<div class="container">
		<%= yield %>
	</div>

<div class="footer">Content &copy 2016</div>
</body>
</html>

app/views/lexicons/index.html.erb
<div class="wrapper">

<% if params[:category] == nil %>
	<h1>All Categories</h1>
<% else %>
	<h1><%= "#{params[:category]}" %></h1>
<% end %>

		<p>Change Categories Below</p>

		<div class="btn"><%= link_to "All Categories", lexicons_path %></div>
		<% @categories.each do |c| %>
					<div class="btn" id="space"><%= link_to c.category, lexicons_path(category: c.category) %></div>
		<% end %>

		<br><br>

	<div class="row">
		<% @lexicons.each do |entry| %>
			<div class="col-md-4">
				<div class="well">
					<% if entry.code.to_s.length < 5 %>
						<h2><%= entry.code.to_s %></h2>
					<% else %>
						<h2><%= entry.code.to_s[0..10] %>...</h2>
					<% end %>
					<h4><%= entry.description.to_s[0..50] %>...</h4>
					<small>Category: <%= entry.category %></small>
					<br><br>
					<div class="btn"><%= link_to "Show", lexicons_show_path(id: entry) %></div>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/lexicons/show.html.erb
<div class="wrapper">

	<h2><%= @lexicon.code %></h2>
	<p><%= @lexicon.description %></p>
	<p><%= @lexicon.category %></p>


	<div class="btn"><%= link_to "<-- Previous Entry", lexicons_show_path(id: @lexicon.id-1) %></div>

	<div class="btn"><%= link_to "Back to Category", lexicons_path(category: @lexicon.category) %></div>

	<div class="btn"><%= link_to "Next Entry -->", lexicons_show_path(id: @lexicon.id+1) %></div>

	<br><br><br>

</div>

app/views/welcome/index.html.erb
<div class="main">
<h1>Code Lexicons</h1>

<h3><%= link_to 'Choose a category to work in, from the beginning', lexicons_path %></h3>
<h3><%= link_to 'Search for specific content', search_path %></h3>
<h3><%= link_to 'Generate a random entry', random_path %></h3>
</div>

app/views/welcome/random.html.erb
<div class="main">
<h1>Random Entry</h1>

	<h2><%= link_to "#{@random.code}", lexicons_show_path(id: @random.id) %></h2>
	<p><%= @random.description %></p>
	<p><%= link_to "#{@random.category}", lexicons_path(category: @random.category) %></p>
	<br>
	<p class="center"><%= link_to "Generate Another Entry!", random_path, class: "btn btn-info" %></p>

</div>

app/views/welcome/results.html.erb
<div class="main">
	
	<h1>Search Results</h1>

	<ul>
		<% @results.each do |r| %>
			<li><h3><%= link_to"#{r.code}", lexicons_show_path(id: r) %></h3>
			<p><%= "#{r.description}" %></p></li>
		<% end %>
	</ul>

</div>

app/views/welcome/search.html.erb
<div class="main">
	<h1>Search For An Entry</h1>

	<br>

	<div class="row">
		<%= form_tag(results_path) do %>
			<div class="form-group col-md-5">
				<%= text_field_tag :search, nil, placeholder: "Search by Code or Description", class: "form-control" %>
			</div>
			<div class="form-group">
				<%= submit_tag "Search", class: "btn btn-primary" %>
			</div>
		<% end %>
	</div>
</div>